server:
  port: ${PORT:9090}

# logging:
#   level:
#     org.atmosphere: warn

spring:
  profiles:
    active:
#      - devDockerPostgres
      - h2
#      - devLocalPostgres

#  mustache:
#    check-template-location: false

# Launch the default browser when starting the application in development mode
#vaadin:
#  launch-browser: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
#  api-docs:
#    path: /v3/api-docs