server:
  port: ${PORT:9090}

# logging:
#   level:
#     org.atmosphere: warn

spring:
  profiles:
    active:
      - devDockerPostgres
#      - h2
#      - devLocalPostgres

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs