server:
  port: ${PORT:9090}

# logging:
#   level:
#     org.atmosphere: warn

spring:
  # H2
  # datasource:
  #   url: jdbc:h2:file:./src/main/resources/db/database;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
  #   driver-class-name: org.h2.Driver
  #   username: 123
  #   password: ""

  # jpa:
  #   database-platform: org.hibernate.dialect.H2Dialect
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  #   open-in-view: false
  #   properties:
  #     hibernate:
  #       format_sql: true

  # h2:
  #   console:
  #     enabled: true
  #    path: /db

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/sb
    username: sa
    password: 
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mustache:
    check-template-location: false

# Launch the default browser when starting the application in development mode
#vaadin:
#  launch-browser: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
#  api-docs:
#    path: /v3/api-docs
